// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBadurAExX4ZFXWGCytIZxevmQRBXBQwQQ',
    appId: '1:474604492516:web:e161ddfc9abae5df53bef1',
    messagingSenderId: '474604492516',
    projectId: 'cluedin-379910',
    authDomain: 'cluedin-379910.firebaseapp.com',
    storageBucket: 'cluedin-379910.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1NH0I6ZKjDTL9d5zxGPSjQveg4tjE0Bs',
    appId: '1:474604492516:android:a9976ab511fcc3a253bef1',
    messagingSenderId: '474604492516',
    projectId: 'cluedin-379910',
    storageBucket: 'cluedin-379910.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQqcwGwJ5ISlbxo-JlZ6rvK1qeYvoRJaM',
    appId: '1:474604492516:ios:5e9f4eb5bef4c09153bef1',
    messagingSenderId: '474604492516',
    projectId: 'cluedin-379910',
    storageBucket: 'cluedin-379910.appspot.com',
    iosBundleId: 'com.example.cluedinApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQqcwGwJ5ISlbxo-JlZ6rvK1qeYvoRJaM',
    appId: '1:474604492516:ios:5e9f4eb5bef4c09153bef1',
    messagingSenderId: '474604492516',
    projectId: 'cluedin-379910',
    storageBucket: 'cluedin-379910.appspot.com',
    iosBundleId: 'com.example.cluedinApp',
  );
}
