// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3_QbP9odQjyQs6bDPf1v9BTaRYx3FXBg',
    appId: '1:100872515087:web:2a417b0b7dbc954886bd7a',
    messagingSenderId: '100872515087',
    projectId: 'cluedin-e47b2',
    authDomain: 'cluedin-e47b2.firebaseapp.com',
    storageBucket: 'cluedin-e47b2.appspot.com',
    measurementId: 'G-SGBHTBP6WD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkhr-cCUjl4BoVYNIWnbDr5iCvPXn1uv0',
    appId: '1:100872515087:android:ba4af5a4003bf98486bd7a',
    messagingSenderId: '100872515087',
    projectId: 'cluedin-e47b2',
    storageBucket: 'cluedin-e47b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8Jzv1c0XwkAzLNLdcag-vEhbyLw6SgX4',
    appId: '1:100872515087:ios:959df518b7798cca86bd7a',
    messagingSenderId: '100872515087',
    projectId: 'cluedin-e47b2',
    storageBucket: 'cluedin-e47b2.appspot.com',
    iosClientId: '100872515087-kf546q4tmedqet89stdp89ma8a6blr3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.cluedinApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8Jzv1c0XwkAzLNLdcag-vEhbyLw6SgX4',
    appId: '1:100872515087:ios:959df518b7798cca86bd7a',
    messagingSenderId: '100872515087',
    projectId: 'cluedin-e47b2',
    storageBucket: 'cluedin-e47b2.appspot.com',
    iosClientId: '100872515087-kf546q4tmedqet89stdp89ma8a6blr3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.cluedinApp',
  );
}
